development:
  adapter: async

test:
<<<<<<< HEAD
  adapter: async
=======
  adapter: test
>>>>>>> 633ac7afe371fce73c509df343575b70c6722552

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
<<<<<<< HEAD
  channel_prefix: final_production
=======
  channel_prefix: project_production
>>>>>>> 633ac7afe371fce73c509df343575b70c6722552
